### ISSUE TITLE
FileChooser Window Open, no success or error callback

### ISSUE THREAD

**Issue by brvier** [MaginSoft/MFileChooser#8]
On Android 4.4 and 4.3 the filechooser open but i callback isn't call (on cyanogen mod 4.4.4 and also genymotion image 4.4.4 and 4.3).

Cordova CLI : 5.4.1
Android platform 4.0.2
TargetSDK API18

**Comment by khertan** [comment]
In adb logcat i can see : 

I/ActivityManager(  390): START u0 {act=android.intent.action.GET_CONTENT cmp=net.khertan.forrunners/com.orleonsoft.android.simplefilechooser.ui.FileChooserActivity} from pid 1880
W/ActivityManager(  390): Activity is launching as a new task, so cancelling activity result.
W/PluginManager( 1880): THREAD WARNING: exec() call to MFileChooser.open blocked the main thread for 160ms. Plugin should use CordovaInterface.getThreadPool().
D/CordovaInterfaceImpl( 1880): Sending activity result to plugin
D/MobileDataStateTracker(  390): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker(  390): default: setPolicyDataEnable(enabled=true)
D/MobileDataStateTracker(  390): default: setPolicyDataEnable(enabled=true)
I/ActivityManager(  390): Displayed net.khertan.forrunners/com.orleonsoft.android.simplefilechooser.ui.FileChooserActivity: +1s495ms
I/FILE CHOOSER( 1880): result ok

**Comment by premtemp1** [comment]
Did you find a solution?

**Comment by khertan** [comment]
Hi,
Yes i use other plugins :)
Benoît HERVIER - http://khertan.net
Le 19 oct. 2016 05:46, premtemp1 <notifications@github.com> a écrit :Did you find a solution?
